# Используем базовый образ Nginx
FROM nginx:latest

# Копируем файл index.html и другие ресурсы в каталог, который обслуживается Nginx
COPY . /usr/share/nginx/html

# Открываем порт 80, чтобы Nginx мог принимать запросы
EXPOSE 80

# Запускаем Nginx в фоновом режиме
CMD ["nginx", "-g", "daemon off;"]